openapi: 3.0.0
info:
  title: Hilite - Addope Integration API
  version: 1.0.0
paths:
  /boards:
    get:
      description: Returns a list of Addope boards registered in Hilite system
      tags:
        - Boards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardsArray'
        '400':
          $ref: '#/components/responses/BadRequest'
  /boards/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      description: Returns details of the board by Id.
      tags:
        - Boards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Board'
        '400':
          $ref: '#/components/responses/BadRequest'
  /boards/{id}/location:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      description: Stores GPS locations of the board. The expected interval of location update is 1 second when the location changes. It is not necessary to send a location when the board does not move.
      tags:
        - Boards
      requestBody:
        content:
          applicaton/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
  /advertisements/{boardId}:
    parameters:
      - name: boardId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - Advertisements
      description: Returns an advertisement for a board to play
      responses:
        '200':
          description: OK
          content:
            appliation/json:
              schema:
                $ref: '#/components/schemas/Advertisement'
        '400':
          $ref: '#/components/responses/BadRequest'
  /playlogs/{boardId}:
    parameters:
      - name: boardId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      tags:
        - Play Logs
      description: Accepts Play Logs as confirmation of play an advertisement by a board
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayLog'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
components:
  schemas:
    Board:
      type: object
      properties:
        id:
          description: Identifier of the board in Hilite system
          type: string
          format: uuid
        externalId:
          description: Identifieer of the board in Addope system
          type: string
          format: text
      required:
        - id
        - boardId
    BoardsArray:
      type: array
      items:
        $ref: '#/components/schemas/Board'
    Location:
      type: object
      properties:
        timestamp:
          description: UTC timestamp when GPS location determined
          type: string
          format: date-time
        lat:
          description: Latitude
          type: number
          format: double
        lng:
          description: Longitude
          type: number
          format: double
      required:
        - timestamp
        - lat
        - lng
    Advertisement:
      type: object
      properties:
        id:
          description: Identifier of the advertisement
          type: string
          format: uuid
        creativeId:
          description: Identifier of the creative
          type: string
          format: uuid
        url:
          description: URL to download the creative
          type: string
          format: uri
        mediaType:
          description: Media type of the creative (Image or Video)
          type: string
          enum:
            - Image
            - Video
        size:
          description: Size of the creative in bytes
          type: integer
        duration:
          description: Time in seconds to play the creative
          type: integer
      required:
        - id
        - creativeId
        - url
        - mediaType
        - size
        - duration
    PlayLog:
      type: object
      properties:
        advertisementId:
          type: string
          format: uuid
          description: Identifier of the played advertisement
        timestamp:
          type: string
          format: date-time
          description: UTC timestamp when the advertisement started to play
      required:
        - advertisementId
        - timestamp
  responses:
    BadRequest:
      description: Bad request
